### ISSUE TITLE
Please add Typescript support 

### ISSUE THREAD

**Issue by LoganBwDE** [xerdnu/react-native-blasted-image#10]
My project is completely using typescript and im getting a Typescript Error for the library :)

/node_modules/react-native-blasted-image/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-blasted-image` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-blasted-image';`ts(7016)

**Comment by xerdnu** [comment]
Added support for typescript in release v1.0.0
