### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by alesdvorakcz** [xerdnu/react-native-blasted-image#12]
Hello, Is there any way how to show custom loading indication while image is loading? I can see OnLoad and OnError callbacks but there is no OnLoadStart

**Comment by Aleksandern** [comment]
and no onLoadEnd

**Comment by fukemy** [comment]
while it's based on `SDWebImage` and `Glide`, you can enable it from native code

**Comment by xerdnu** [comment]
The main purpose of the component is to show the images in such speed that you never need a loading indicator. I would recommend you to preload the images if you have the need for a loading indicator.

Best regards!
