### ISSUE TITLE
[Android]crash with You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by boboxiaodd** [xerdnu/react-native-blasted-image#13]
App in background, some times crash with this:

```
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:366)
```

https://github.com/xerdnu/react-native-blasted-image/blob/ff9d739e1a0500095394a8d82cb3f1973d395d94/android/src/main/java/com/reactlibrary/BlastedViewManager.java#L37

maybe check `view.getContext()  != null`

**Comment by xerdnu** [comment]
Fixed in release v1.0.0
