### ISSUE TITLE
How to use without caching images?

### ISSUE THREAD

**Issue by qnrjs42** [xerdnu/react-native-blasted-image#14]
My app has thousands of remote images.
Caching thousands of images will cause the app to shut down due to lack of memory.
Is there a way to quickly import images and just render them without caching them?

**Comment by mrJolla** [comment]
I could be wrong, but I think this example will help you https://github.com/xerdnu/react-native-blasted-image?tab=readme-ov-file#events

**Comment by xerdnu** [comment]
@qnrjs42 You can set skipMemory to false and the image will only be cached to disk. More info in the docs :)

🚀 Best regards

**Comment by xerdnu** [comment]
@qnrjs42 You can set skipMemoryCache to false and the image will only be cached to disk. More info in the docs :)

🚀 Best regards
