### ISSUE TITLE
Future react-native major releases to discontinue support for `defaultProps`

### ISSUE THREAD

**Issue by longnguyen2508** [xerdnu/react-native-blasted-image#16]
Upon updating to react-native version 0.74.0, the following warning was encountered:

>  ERROR  Warning: BlastedImage: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by bigriot** [comment]
It's kind of troubling that an issue with such an easy fix is not being addressed yet. I'm willing to make the necessary changes but wondering if it would help at all seeing there's two pending pull requests that haven't been addressed since March.....

**Comment by xerdnu** [comment]
Fixed in the latest release and sorry for the late response.

Best regards 🚀

**Comment by longnguyen2508** [comment]
Thank you :bow:
