### ISSUE TITLE
Change source if image has error

### ISSUE THREAD

**Issue by toantk911** [xerdnu/react-native-blasted-image#5]
Hi @xerdnu 

I'm handling error by updating a new source but the BlastedImage keeps showing the error icon.

I've created a pull request to fix this. Could you please check?
https://github.com/xerdnu/react-native-blasted-image/pull/4

**Comment by xerdnu** [comment]
Hi @toantk911 

I have been pretty busy so i am sorry for the late response but i merged this in [v0.0.13]

Thanks!  🚀

[v0.0.13]: https://github.com/xerdnu/react-native-blasted-image/compare/v0.0.12...v0.0.13
