### ISSUE TITLE
Add createAnimatedComponent support

### ISSUE THREAD

**Issue by boboxiaodd** [xerdnu/react-native-blasted-image#9]
i want to animate a image , but got an error:
```
createAnimatedComponent does not support stateless functional components; use a class instead.
```

https://github.com/facebook/react-native/issues/22066

**Comment by andresdegano** [comment]
Is this feature implemented? I came across the same issue trying to animete an image

**Comment by xerdnu** [comment]
@andresdegano 

Animated images should be supported, yes.

Could you please add a minimal reproducible example?

Best regards!
